name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      # FIXME: workaround for backend partial config limitation (see https://github.com/hashicorp/terraform/issues/21830)
      - name: Prepare Terraform Backend
        run: |
          echo "workspaces { name = \"${{ secrets.TERRAFORM_CLOUD_WORKSPACE }}\" }" >>backend.hcl
        working-directory: ./infra

      - name: Initalize Terraform
        run: |
          terraform init \
            -backend-config=backend.hcl \
            -backend-config="organization=${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}" \
        working-directory: ./infra

      # FIXME: workaround for remote backend limitation (Error: Run variables are currently not supported)
      - name: Prepare Terraform Variables
        run: |
          echo "digitalocean_token = \"${{ secrets.DIGITALOCEAN_TOKEN }}\"" >>github_actions.auto.tfvars
        working-directory: ./infra

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve
        working-directory: ./infra
