name: Review

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-actions:
    name: Lint GitHub Actions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm --global install prettier

      - name: Lint workflow code
        run: prettier --check .github

  lint-docs:
    name: Lint Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm --global install prettier

      - name: Lint markdown
        run: prettier --check **.md

  lint-iac:
    name: Lint IaC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Lint Terraform code
        run: terraform fmt -recursive -check
        working-directory: ./infra

  validate-iac:
    name: Validate IaC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initalize Terraform
        run: terraform init -backend=false
        working-directory: ./infra

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./infra

  plan:
    name: Plan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      # FIXME: workaround for backend partial config limitation (see https://github.com/hashicorp/terraform/issues/21830)
      - name: Prepare Terraform Backend
        run: |
          echo "workspaces { name = \"${{ secrets.TERRAFORM_CLOUD_WORKSPACE }}\" }" >>backend.hcl
        working-directory: ./infra

      - name: Initalize Terraform
        run: |
          terraform init \
            -backend-config=backend.hcl \
            -backend-config="organization=${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}" \
        working-directory: ./infra

      # FIXME: workaround for remote backend limitation (Error: Run variables are currently not supported)
      - name: Prepare Terraform Variables
        run: |
          echo "digitalocean_token = \"${{ secrets.DIGITALOCEAN_TOKEN }}\"" >>github_actions.auto.tfvars
        working-directory: ./infra

      - name: Render Plan
        run: |
          terraform plan
        working-directory: ./infra
